# -*- coding:utf-8 -*-



lagou_json = {
  "msg":None,
  "success":True,
  "requestId":None,
  "resubmitToken":None,
  "content": {
    "pageNo": 1,
    "pageSize": 15,
    "hrInfoMap": {
      "1276951": {
        "userId": 738560,
        "positionName": "CEO",
        "phone":None,
        "portrait": "image1/M00/1F/85/CgYXBlUz00KAYxFyAAON6IAmufY944.png",
        "receiveEmail":None,
        "realName": "陈沧",
        "userLevel": "G1",
        "canTalk":True
      },
      "1795456": {
        "userId": 1588078,
        "positionName": "CTO",
        "phone":None,
        "portrait":None,
        "receiveEmail":None,
        "realName": "weiliang",
        "userLevel": "G1",
        "canTalk":True
      },
      "2012662": {
        "userId": 1676587,
        "positionName": "新世界教育集团",
        "phone":None,
        "portrait":None,
        "receiveEmail":None,
        "realName": "王女士",
        "userLevel": "G1",
        "canTalk":True
      },
      "2077201": {
        "userId": 5297120,
        "positionName": "HR",
        "phone":None,
        "portrait": "i/image/M00/35/E5/CgqKkVdcx8OAbYMXAABKPLmwoMg747.jpg",
        "receiveEmail":None,
        "realName": "Jane",
        "userLevel": "G1",
        "canTalk":True
      },
      "2380097": {
        "userId": 2082998,
        "positionName": "人力资源总监",
        "phone":None,
        "portrait": "i/image/M00/01/EF/CgqKkVZ7ngeATF85AABZEiDMbVQ42.jpeg",
        "receiveEmail":None,
        "realName": "武青",
        "userLevel": "G1",
        "canTalk":True
      },
      "2614074": {
        "userId": 5932812,
        "positionName": "招聘主管",
        "phone":None,
        "portrait": "i/image/M00/50/8A/CgqKkVe0KHCAIInAAABSZITLREE74.jpeg",
        "receiveEmail":None,
        "realName": "Ada",
        "userLevel": "G1",
        "canTalk":True
      },
      "2679124": {
        "userId": 602053,
        "positionName": "招聘专员",
        "phone":None,
        "portrait": "i/image/M00/37/92/CgqKkVdgx9mAdVSRAACI7W42bI4259.jpg",
        "receiveEmail":None,
        "realName": "51Talk无忧英语",
        "userLevel": "G1",
        "canTalk":True
      },
      "2713713": {
        "userId": 6409565,
        "positionName":None,
        "phone":None,
        "portrait":None,
        "receiveEmail":None,
        "realName": "zhaopin",
        "userLevel": "G1",
        "canTalk":True
      },
      "2718486": {
        "userId": 4555943,
        "positionName":None,
        "phone":None,
        "portrait":None,
        "receiveEmail":None,
        "realName": "Liz",
        "userLevel": "G1",
        "canTalk":True
      },
      "2726734": {
        "userId": 896988,
        "positionName": "招聘主管",
        "phone":None,
        "portrait":None,
        "receiveEmail":None,
        "realName": "杜老师",
        "userLevel": "G1",
        "canTalk":True
      },
      "2739446": {
        "userId": 6802872,
        "positionName": "项目经理",
        "phone":None,
        "portrait": "i/image/M00/8D/6A/CgqKkViHBoCALMtOAABP8VxCIWg302.png",
        "receiveEmail":None,
        "realName": "清晨",
        "userLevel": "G1",
        "canTalk":True
      },
      "2739706": {
        "userId": 57680,
        "positionName": "HR",
        "phone":None,
        "portrait":None,
        "receiveEmail":None,
        "realName": "荣女士",
        "userLevel": "G1",
        "canTalk":True
      },
      "2739785": {
        "userId": 6530771,
        "positionName": "出版发行、编辑",
        "phone":None,
        "portrait":None,
        "receiveEmail":None,
        "realName": "余敏保",
        "userLevel": "G1",
        "canTalk":True
      },
      "2739817": {
        "userId": 728088,
        "positionName":None,
        "phone":None,
        "portrait":None,
        "receiveEmail":None,
        "realName": "hr",
        "userLevel": "G1",
        "canTalk":True
      },
      "2739945": {
        "userId": 988477,
        "positionName": "HRM",
        "phone":None,
        "portrait":None,
        "receiveEmail":None,
        "realName": "wubinhua",
        "userLevel": "G1",
        "canTalk":True
      }
    },
    "positionResult": {
      "totalCount": 4981,
      "resultSize": 15,
      "locationInfo": {
        "locationCode":None,
        "businessZone":None,
        "city": "北京",
        "district":None,
        "queryByGisCode":False
      },
      "queryAnalysisInfo": {
        "industryName":None,
        "positionName":None,
        "companyName":None,
        "usefulCompany":False
      },
      "strategyProperty": {
        "name": "dm-csearch-newSimScorer",
        "id": 1
      },
      "result"
      : [
        {
          "companyId": 6040,
          "positionName": "运营实习生",
          "workYear": "不限",
          "education": "不限",
          "jobNature": "全职",
          "companyLogo": "image1/M00/0C/6C/Cgo8PFT1X2uAUbGsAABCAddtkWg960.jpg",
          "industryField": "移动互联网,教育",
          "financeStage": "成长型(不需要融资)",
          "city": "北京",
          "salary": "2k-3k",
          "positionId": 2739945,
          "companyShortName": "慕课网",
          "positionAdvantage": "团队氛围好,发展空间大",
          "createTime": "2017-01-25 10:11:25",
          "district": "西城区",
          "companyLabelList": [
            "节日礼物",
            "技能培训",
            "节日礼品卡",
            "月度团建"
          ],
          "approve": 1,
          "companySize": "50-150人",
          "score": 0,
          "formatCreateTime": "10:11发布",
          "businessZones": [
            "马甸",
            "德胜门",
            "北太平庄"
          ],
          "imState": "today",
          "lastLogin": 1485309383000,
          "publisherId": 988477,
          "explain":None,
          "plus":None,
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0,
          "gradeDescription":None,
          "promotionScoreExplain":None,
          "firstType": "运营/编辑/客服",
          "secondType": "运营",
          "positionLables": [
            "实习生",
            "运营"
          ],
          "companyFullName": "北京慕课科技中心",
          "adWord": 0
        },
        {
          "companyId": 52218,
          "positionName": "Golang",
          "workYear": "3-5年",
          "education": "不限",
          "jobNature": "全职",
          "companyLogo": "image1/M00/08/DC/CgYXBlTYb5qAKM8YAABEA5dLaas438.jpg",
          "industryField": "教育",
          "financeStage": "初创型(未融资)",
          "city": "北京",
          "salary": "20k-40k",
          "positionId": 2077201,
          "companyShortName": "迈瑞科",
          "positionAdvantage": "扁平管理，团队年轻，晋升空间大",
          "createTime": "2017-01-25 09:54:42",
          "district": "朝阳区",
          "companyLabelList": [
            "专项奖金",
            "绩效奖金",
            "岗位晋升",
            "五险一金"
          ],
          "approve": 1,
          "companySize": "15-50人",
          "score": 0,
          "formatCreateTime": "09:54发布",
          "businessZones":None,
          "imState": "today",
          "lastLogin": 1485309227000,
          "publisherId": 5297120,
          "explain":None,
          "plus":None,
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0,
          "gradeDescription":None,
          "promotionScoreExplain":None,
          "firstType": "技术",
          "secondType": "后端开发",
          "positionLables": [
            "后端开发",
            "技术"
          ],
          "companyFullName": "北京迈瑞科教育科技有限公司",
          "adWord": 0
        },
        {
          "companyId": 155709,
          "positionName": "商务BD（酒店旅游方向）",
          "workYear": "1-3年",
          "education": "大专",
          "jobNature": "全职",
          "companyLogo": "i/image/M00/6B/A7/Cgp3O1ga9faAG_TzAAEb3SjbTDg470.png",
          "industryField": "移动互联网,教育",
          "financeStage": "初创型(天使轮)",
          "city": "北京",
          "salary": "5k-10k",
          "positionId": 2713713,
          "companyShortName": "乐学营",
          "positionAdvantage": "扁平化管理,五险一金,弹性工作,补助",
          "createTime": "2017-01-25 09:25:17",
          "district": "朝阳区",
          "companyLabelList":None,
          "approve": 0,
          "companySize": "15-50人",
          "score": 0,
          "formatCreateTime": "09:25发布",
          "businessZones": [
            "团结湖"
          ],
          "imState": "disabled",
          "lastLogin": 1485307427000,
          "publisherId": 6409565,
          "explain":None,
          "plus":None,
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0,
          "gradeDescription":None,
          "promotionScoreExplain":None,
          "firstType": "市场/商务/销售类",
          "secondType": "商务拓展/BD",
          "positionLables": [
            "渠道",
            "商务",
            "商务拓展",
            "BD",
            "旅游"
          ],
          "companyFullName": "北京乐学游文化发展有限公司",
          "adWord": 0
        },
        {
          "companyId": 39721,
          "positionName": "高级营销策划经理",
          "workYear": "5-10年",
          "education": "本科",
          "jobNature": "全职",
          "companyLogo": "i/image/M00/7F/92/CgqKkVhOXXGAMCUhAAATqyPeN-8515.png",
          "industryField": "教育",
          "financeStage": "成长型(不需要融资)",
          "city": "北京",
          "salary": "12k-24k",
          "positionId": 2739817,
          "companyShortName": "萝卜教育网",
          "positionAdvantage": "福利多,薪水高,老板好",
          "createTime": "2017-01-24 21:27:56",
          "district": "海淀区",
          "companyLabelList": [
            "节日礼物",
            "带薪年假",
            "绩效奖金",
            "岗位晋升"
          ],
          "approve": 1,
          "companySize": "50-150人",
          "score": 0,
          "formatCreateTime": "1天前发布",
          "businessZones": [
            "中关村",
            "北京大学",
            "苏州街"
          ],
          "imState": "disabled",
          "lastLogin": 1485264511000,
          "publisherId": 728088,
          "explain":None,
          "plus":None,
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0,
          "gradeDescription":None,
          "promotionScoreExplain":None,
          "firstType": "市场/商务/销售类",
          "secondType": "市场/营销",
          "positionLables": [
            "总监",
            "文案",
            "市场",
            "经理",
            "营销",
            "整合营销"
          ],
          "companyFullName": "北京萝卜来了教育科技有限公司",
          "adWord": 0
        },
        {
          "companyId": 159237,
          "positionName": "出版发行",
          "workYear": "不限",
          "education": "大专",
          "jobNature": "全职",
          "companyLogo": "images/logo_default.png",
          "industryField": "教育",
          "financeStage": "成长型(不需要融资)",
          "city": "北京",
          "salary": "4K-8K",
          "positionId": 2739785,
          "companyShortName": "煊坤博文",
          "positionAdvantage": "稳定有前景",
          "createTime": "2017-01-24 19:35:28",
          "district": "昌平区",
          "companyLabelList":None,
          "approve": 0,
          "companySize": "150-500人",
          "score": 0,
          "formatCreateTime": "1天前发布",
          "businessZones": [
            "回龙观"
          ],
          "imState": "today",
          "lastLogin": 1485270079000,
          "publisherId": 6530771,
          "explain":None,
          "plus":None,
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0,
          "gradeDescription":None,
          "promotionScoreExplain":None,
          "firstType": "其它",
          "secondType": "教育|培训",
          "positionLables": [
            "教材编辑出版发"
          ],
          "companyFullName": "煊坤博文图书有限公司",
          "adWord": 0
        },
        {
          "companyId": 5706,
          "positionName": "数学教学设计实习生",
          "workYear": "不限",
          "education": "本科",
          "jobNature": "实习",
          "companyLogo": "i/image/M00/01/FA/Cgp3O1Z9BXWALko8AACyUeZ468w175.png",
          "industryField": "移动互联网,教育",
          "financeStage": "成长型(B轮)",
          "city": "北京",
          "salary": "2k-3k",
          "positionId": 2739706,
          "companyShortName": "洋葱数学",
          "positionAdvantage": "免费早午餐,大牛团队,成长空间",
          "createTime": "2017-01-24 18:10:37",
          "district": "西城区",
          "companyLabelList": [
            "产品领先行业",
            "关注学习本源",
            "明星跨界团队",
            "股票期权"
          ],
          "approve": 1,
          "companySize": "50-150人",
          "score": 0,
          "formatCreateTime": "1天前发布",
          "businessZones": [
            "虎坊桥",
            "大栅栏",
            "前门"
          ],
          "imState": "today",
          "lastLogin": 1485310860000,
          "publisherId": 57680,
          "explain":None,
          "plus":None,
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0,
          "gradeDescription":None,
          "promotionScoreExplain":None,
          "firstType": "运营/编辑/客服",
          "secondType": "编辑",
          "positionLables": [
            "实习生",
            "内容"
          ],
          "companyFullName": "光合新知（北京）科技有限公司",
          "adWord": 0
        },
        {
          "companyId": 3328,
          "positionName": "集团总部--预算分析主管",
          "workYear": "3-5年",
          "education": "本科",
          "jobNature": "全职",
          "companyLogo": "image1/M00/00/09/Cgo8PFTUWBGALraJAAAeTBKK4IU791.png",
          "industryField": "移动互联网,教育",
          "financeStage": "上市公司",
          "city": "北京",
          "salary": "10k-15k",
          "positionId": 2718486,
          "companyShortName": "好未来",
          "positionAdvantage": "财务预算分析主管",
          "createTime": "2017-01-24 17:16:48",
          "district": "海淀区",
          "companyLabelList": [
            "上市公司",
            "领军企业",
            "五险一金",
            "住福计划"
          ],
          "approve": 1,
          "companySize": "2000人以上",
          "score": 0,
          "formatCreateTime": "1天前发布",
          "businessZones":None,
          "imState": "today",
          "lastLogin": 1485249123000,
          "publisherId": 4555943,
          "explain":None,
          "plus":None,
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0,
          "gradeDescription":None,
          "promotionScoreExplain":None,
          "firstType": "综合职能类",
          "secondType": "财务",
          "positionLables": [
            "财务"
          ],
          "companyFullName": "北京世纪好未来教育科技有限公司",
          "adWord": 0
        },
        {
          "companyId": 167237,
          "positionName": "UI设计师(心理游戏)",
          "workYear": "不限",
          "education": "不限",
          "jobNature": "全职",
          "companyLogo": "i/image/M00/8D/6A/CgqKkViHBvKAXDp3AABP8VxCIWg235.png",
          "industryField": "教育,移动互联网",
          "financeStage": "成长型(不需要融资)",
          "city": "北京",
          "salary": "12k-20k",
          "positionId": 2739446,
          "companyShortName": "知新树",
          "positionAdvantage": "发挥创意,弹性工作,人性关怀,职业规划",
          "createTime": "2017-01-24 16:21:56",
          "district": "海淀区",
          "companyLabelList": [
            "专项奖金",
            "绩效奖金",
            "定期体检",
            "弹性工作"
          ],
          "approve": 0,
          "companySize": "50-150人",
          "score": 0,
          "formatCreateTime": "1天前发布",
          "businessZones": [
            "花园桥"
          ],
          "imState": "disabled",
          "lastLogin": 1485243956000,
          "publisherId": 6802872,
          "explain":None,
          "plus":None,
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0,
          "gradeDescription":None,
          "promotionScoreExplain":None,
          "firstType": "设计类",
          "secondType": "UI/UE/GUI/交互",
          "positionLables": [
            "高级",
            "游戏",
            "app",
            "专员",
            "UI"
          ],
          "companyFullName": "北京知新树科技有限公司",
          "adWord": 0
        },
        {
          "companyId": 119153,
          "positionName": "BPM功能顾问",
          "workYear": "5-10年",
          "education": "本科",
          "jobNature": "全职",
          "companyLogo": "i/image/M00/12/D3/Cgp3O1bmVr-AOGHYAABsWK_3bSI050.JPG",
          "industryField": "移动互联网,教育",
          "financeStage": "上市公司",
          "city": "北京",
          "salary": "15k-30k",
          "positionId": 2679124,
          "companyShortName": "51Talk 无忧英语",
          "positionAdvantage": "与业界大牛一起共事",
          "createTime": "2017-01-24 15:02:39",
          "district": "海淀区",
          "companyLabelList": [
            "带薪年假",
            "股票期权",
            "绩效奖金",
            "定期体检"
          ],
          "approve": 0,
          "companySize": "2000人以上",
          "score": 0,
          "formatCreateTime": "1天前发布",
          "businessZones": [
            "上地"
          ],
          "imState": "today",
          "lastLogin": 1485247005000,
          "publisherId": 602053,
          "explain":None,
          "plus":None,
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0,
          "gradeDescription":None,
          "promotionScoreExplain":None,
          "firstType": "产品/需求/项目类",
          "secondType": "项目管理",
          "positionLables": [
            "项目管理",
            "风控",
            "产品经理",
            "顾问"
          ],
          "companyFullName": "北京大生在线科技有限公司",
          "adWord": 0
        },
        {
          "companyId": 63714,
          "positionName": "自然语言处理",
          "workYear": "不限",
          "education": "硕士",
          "jobNature": "全职",
          "companyLogo": "i/image/M00/59/0B/CgqKkVfWgPaAdaAxAAAq6WYoG_0975.png",
          "industryField": "移动互联网,教育",
          "financeStage": "成长型(不需要融资)",
          "city": "北京",
          "salary": "25k-50k",
          "positionId": 1795456,
          "companyShortName": "粉笔网",
          "positionAdvantage": "待遇丰厚，发展空间巨大",
          "createTime": "2017-01-24 14:43:28",
          "district": "朝阳区",
          "companyLabelList": [
            "技能培训",
            "节日礼物",
            "年底双薪",
            "带薪年假"
          ],
          "approve": 0,
          "companySize": "50-150人",
          "score": 0,
          "formatCreateTime": "1天前发布",
          "businessZones": [
            "三里屯",
            "工体",
            "团结湖"
          ],
          "imState": "today",
          "lastLogin": 1485303411000,
          "publisherId": 1588078,
          "explain":None,
          "plus":None,
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0,
          "gradeDescription":None,
          "promotionScoreExplain":None,
          "firstType": "技术",
          "secondType": "高端技术职位",
          "positionLables": [
            "NLP",
            "算法"
          ],
          "companyFullName": "北京粉笔蓝天科技有限公司",
          "adWord": 0
        },
        {
          "companyId": 46442,
          "positionName": "前端开发工程师",
          "workYear": "3-5年",
          "education": "大专",
          "jobNature": "全职",
          "companyLogo": "i/image/M00/00/38/Cgp3O1Y2xeGAS1CIAAIz8cZDftw605.jpg",
          "industryField": "移动互联网,教育",
          "financeStage": "上市公司",
          "city": "北京",
          "salary": "8k-12k",
          "positionId": 2726734,
          "companyShortName": "文都教育",
          "positionAdvantage": "带薪年假,氛围轻松,地铁周边",
          "createTime": "2017-01-24 11:36:17",
          "district": "海淀区",
          "companyLabelList": [
            "技能培训",
            "年底双薪",
            "绩效奖金",
            "岗位晋升"
          ],
          "approve": 1,
          "companySize": "500-2000人",
          "score": 0,
          "formatCreateTime": "1天前发布",
          "businessZones": [
            "航天桥",
            "花园桥",
            "紫竹桥"
          ],
          "imState": "today",
          "lastLogin": 1485228974000,
          "publisherId": 896988,
          "explain":None,
          "plus":None,
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0,
          "gradeDescription":None,
          "promotionScoreExplain":None,
          "firstType": "开发/测试/运维类",
          "secondType": "前端开发/移动开发",
          "positionLables": [
            "web前端",
            "前端",
            "Html5/CSS3"
          ],
          "companyFullName": "北京世纪文都教育科技发展有限公司",
          "adWord": 0
        },
        {
          "companyId": 54634,
          "positionName": "市场经理",
          "workYear": "3-5年",
          "education": "本科",
          "jobNature": "全职",
          "companyLogo": "image1/M00/0D/15/Cgo8PFT2xWmActcaAAB1CkpzVSg665.jpg",
          "industryField": "教育",
          "financeStage": "成长型(A轮)",
          "city": "北京",
          "salary": "10k-20k",
          "positionId": 2614074,
          "companyShortName": "译泰教育",
          "positionAdvantage": "扁平管理,晋升空间大,领导专业,资源丰富",
          "createTime": "2017-01-24 11:22:54",
          "district": "朝阳区",
          "companyLabelList": [
            "领导好",
            "技能培训",
            "五险一金",
            "交通补助"
          ],
          "approve": 1,
          "companySize": "50-150人",
          "score": 0,
          "formatCreateTime": "1天前发布",
          "businessZones": [
            "来广营",
            "望京"
          ],
          "imState": "today",
          "lastLogin": 1485227624000,
          "publisherId": 5932812,
          "explain":None,
          "plus":None,
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0,
          "gradeDescription":None,
          "promotionScoreExplain":None,
          "firstType": "市场/商务/销售类",
          "secondType": "市场/营销",
          "positionLables": [
            "经理",
            "市场",
            "教育",
            "K12"
          ],
          "companyFullName": "北京译泰教育科技有限公司",
          "adWord": 0
        },
        {
          "companyId": 68888,
          "positionName": "电话客服/电话邀约 五险一金+早十晚五+带薪年假",
          "workYear": "不限",
          "education": "不限",
          "jobNature": "全职",
          "companyLogo": "images/logo_default.png",
          "industryField": "教育",
          "financeStage": "上市公司",
          "city": "北京",
          "salary": "5k-7k",
          "positionId": 2012662,
          "companyShortName": "新世界教育集团",
          "positionAdvantage": "无责底薪+提成+团队奖金+签单奖金+TOP奖金",
          "createTime": "2017-01-24 11:21:52",
          "district":None,
          "companyLabelList": [
            "技能培训",
            "带薪年假",
            "绩效奖金",
            "岗位晋升"
          ],
          "approve": 0,
          "companySize": "2000人以上",
          "score": 0,
          "formatCreateTime": "1天前发布",
          "businessZones":None,
          "imState": "today",
          "lastLogin": 1485227893000,
          "publisherId": 1676587,
          "explain":None,
          "plus":None,
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0,
          "gradeDescription":None,
          "promotionScoreExplain":None,
          "firstType": "运营",
          "secondType": "客服",
          "positionLables": [
            "客服"
          ],
          "companyFullName": "北京市朝阳区新世界培训学校",
          "adWord": 0
        },
        {
          "companyId": 40080,
          "positionName": "销售专员",
          "workYear": "不限",
          "education": "不限",
          "jobNature": "全职",
          "companyLogo": "image1/M00/00/62/Cgo8PFTUXVWAJ1D4AAA-bK8vVo0364.jpg",
          "industryField": "教育",
          "financeStage": "初创型(未融资)",
          "city": "北京",
          "salary": "8k-10k",
          "positionId": 1276951,
          "companyShortName": "考试星",
          "positionAdvantage": "提成高 订单额20%起",
          "createTime": "2017-01-24 11:21:06",
          "district": "朝阳区",
          "companyLabelList": [
            "节日礼物",
            "技能培训",
            "股票期权",
            "专项奖金"
          ],
          "approve": 1,
          "companySize": "少于15人",
          "score": 0,
          "formatCreateTime": "1天前发布",
          "businessZones": [
            "柳芳",
            "和平里",
            "左家庄"
          ],
          "imState": "today",
          "lastLogin": 1485264975000,
          "publisherId": 738560,
          "explain":None,
          "plus":None,
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0,
          "gradeDescription":None,
          "promotionScoreExplain":None,
          "firstType": "市场与销售",
          "secondType": "销售",
          "positionLables": [
            "销售"
          ],
          "companyFullName": "北京梦见星科技有限公司",
          "adWord": 0
        },
        {
          "companyId": 81904,
          "positionName": "U3D",
          "workYear": "1-3年",
          "education": "本科",
          "jobNature": "全职",
          "companyLogo": "image1/M00/36/55/Cgo8PFWeHj6AUN2nAABTTt7sNEo961.jpg?cc=0.33867357997223735",
          "industryField": "教育,游戏",
          "financeStage": "初创型(天使轮)",
          "city": "北京",
          "salary": "18k-25k",
          "positionId": 2380097,
          "companyShortName": "创优天下",
          "positionAdvantage": "专注游戏，团队氛围好，学习提升快",
          "createTime": "2017-01-24 11:11:53",
          "district": "海淀区",
          "companyLabelList": [
            "带薪年假",
            "绩效奖金",
            "扁平管理",
            "管理规范"
          ],
          "approve": 1,
          "companySize": "50-150人",
          "score": 0,
          "formatCreateTime": "1天前发布",
          "businessZones": [
            "双安",
            "中关村",
            "双榆树"
          ],
          "imState": "today",
          "lastLogin": 1485243089000,
          "publisherId": 2082998,
          "explain":None,
          "plus":None,
          "pcShow": 0,
          "appShow": 0,
          "deliver": 0,
          "gradeDescription":None,
          "promotionScoreExplain":None,
          "firstType": "技术",
          "secondType": "前端开发/移动开发",
          "positionLables": [
            "U3D",
            "游戏"
          ],
          "companyFullName": "北京创优天下网络科技有限公司",
          "adWord": 0
        }
      ]

    }
  },
  "code": 0
}